server:
  port: 8080

spring:
  application:
    name: backend
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/wdd?useSSL=false&serverTimezone=UTC
    username: app
    password: "1234"
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
