services:
  mysql:
    image: mysql:8.0.36
    container_name: wdd-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: wdd
      MYSQL_USER: app
      MYSQL_PASSWORD: "1234"
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mysql/initdb:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
